# Generated by Django 4.2.6 on 2024-02-03 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0002_alter_shopcustomer_user'),
        ('Ticketshop', '0003_myticket_bought_myticket_reserved_and_more'),
        ('Orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartSeasonTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.ManyToManyField(to='Ticketshop.myticket')),
            ],
        ),
        migrations.CreateModel(
            name='CartSingleTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.ManyToManyField(to='Ticketshop.myticket')),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='seasonticket',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tickets',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Customers.shopcustomer'),
        ),
        migrations.DeleteModel(
            name='OrderPosition',
        ),
        migrations.AddField(
            model_name='order',
            name='items1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Orders.cartsingleticket'),
        ),
        migrations.AddField(
            model_name='order',
            name='items2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Orders.cartseasonticket'),
        ),
    ]
