# Generated by Django 4.2.5 on 2023-11-25 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticketshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseticket',
            name='Ticketid',
            field=models.CharField(default='8B398026DC', editable=False, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='seasonticket',
            name='seasonTicketid',
            field=models.CharField(default='B66B12DE42', editable=False, max_length=10, primary_key=True, serialize=False),
        ),
    ]
