# Generated by Django 4.2.6 on 2023-10-26 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=50)),
                ('matchName', models.CharField(max_length=50)),
                ('eventTime', models.DateTimeField(auto_now_add=True)),
                ('capacity', models.IntegerField(default=30)),
                ('capacityFanSector', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='SeasonTicket',
            fields=[
                ('seasonTicketid', models.CharField(default='84D011EADD', editable=False, max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('price', models.IntegerField(default=300)),
            ],
        ),
        migrations.CreateModel(
            name='BaseTicket',
            fields=[
                ('Ticketid', models.CharField(default='6404A83A72', editable=False, max_length=10, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'products_base',
                'swappable': 'PRODUCT_MODEL',
            },
        ),
        migrations.CreateModel(
            name='MyTicket',
            fields=[
                ('baseticket_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Ticketshop.baseticket')),
                ('used', models.BooleanField(auto_created=True, default=False)),
                ('price', models.IntegerField(default=30)),
                ('matchEvent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Ticketshop.match')),
                ('seasonCard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Ticketshop.seasonticket')),
            ],
            options={
                'db_table': 'pages_ticketbase',
            },
            bases=('Ticketshop.baseticket',),
        ),
    ]
