# Generated by Django 4.2.6 on 2023-10-26 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticketshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseticket',
            name='Ticketid',
            field=models.CharField(default='7DEC8A9403', editable=False, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='seasonticket',
            name='seasonTicketid',
            field=models.CharField(default='384AC74B38', editable=False, max_length=10, primary_key=True, serialize=False),
        ),
    ]
