# Generated by Django 4.2.6 on 2024-02-03 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticketshop', '0002_alter_baseticket_ticketid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myticket',
            name='bought',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='myticket',
            name='reserved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='myticket',
            name='ticketType',
            field=models.CharField(default='Ticket', max_length=30),
        ),
        migrations.AddField(
            model_name='seasonticket',
            name='bought',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seasonticket',
            name='reserved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seasonticket',
            name='ticketType',
            field=models.CharField(default='Season Ticket', max_length=30),
        ),
        migrations.AlterField(
            model_name='baseticket',
            name='Ticketid',
            field=models.CharField(editable=False, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='seasonticket',
            name='seasonTicketid',
            field=models.CharField(default='67AB9941E4', editable=False, max_length=10, primary_key=True, serialize=False),
        ),
    ]
