# Generated by Django 4.2.6 on 2024-02-03 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticketshop', '0003_myticket_bought_myticket_reserved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seasonticket',
            name='seasonTicketid',
            field=models.CharField(default='E093422442', editable=False, max_length=10, primary_key=True, serialize=False),
        ),
    ]
