# Generated by Django 4.2.6 on 2024-02-03 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0004_remove_shopcustomer_orderedseasontickets_and_more'),
        ('Ticketshop', '0004_alter_seasonticket_seasonticketid'),
    ]

    operations = [
        migrations.AddField(
            model_name='myticket',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Customers.shopcustomer'),
        ),
        migrations.AddField(
            model_name='seasonticket',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Customers.shopcustomer'),
        ),
        migrations.AlterField(
            model_name='seasonticket',
            name='seasonTicketid',
            field=models.CharField(default='77BE702041', editable=False, max_length=10, primary_key=True, serialize=False),
        ),
    ]
