# Generated by Django 4.2.6 on 2024-02-03 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticketshop', '0005_myticket_buyer_seasonticket_buyer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myticket',
            name='ticketType',
        ),
        migrations.RemoveField(
            model_name='seasonticket',
            name='ticketType',
        ),
        migrations.AddField(
            model_name='match',
            name='sector',
            field=models.CharField(default='A', max_length=2),
        ),
        migrations.AlterField(
            model_name='seasonticket',
            name='seasonTicketid',
            field=models.CharField(default='BAC80E5604', editable=False, max_length=10, primary_key=True, serialize=False),
        ),
    ]
