# Generated by Django 4.2.6 on 2024-02-03 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticketshop', '0006_remove_myticket_tickettype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seasonticket',
            name='seasonTicketid',
            field=models.CharField(default='1111329195', editable=False, max_length=10, primary_key=True, serialize=False),
        ),
    ]
