# Generated by Django 4.2.6 on 2024-02-03 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticketshop', '0008_remove_match_capacity_remove_match_capacityfansector_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seasonticket',
            name='seasonTicketid',
            field=models.CharField(default='1CA8A89D86', editable=False, max_length=10, primary_key=True, serialize=False),
        ),
    ]
