# Generated by Django 4.2.6 on 2024-02-03 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticketshop', '0009_alter_seasonticket_seasonticketid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seasonticket',
            name='seasonTicketid',
            field=models.CharField(default='0BF7B80064', editable=False, max_length=10, primary_key=True, serialize=False),
        ),
    ]
