# Generated by Django 4.2.6 on 2024-02-03 22:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticketshop', '0010_alter_seasonticket_seasonticketid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='eventTime',
            field=models.DateField(default=datetime.date(2024, 3, 3)),
        ),
        migrations.AlterField(
            model_name='seasonticket',
            name='seasonTicketid',
            field=models.CharField(default='0120EFAB37', editable=False, max_length=10, primary_key=True, serialize=False),
        ),
    ]
