# Generated by Django 4.2.6 on 2024-02-03 23:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticketshop', '0011_alter_match_eventtime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='eventTime',
            field=models.DateField(default=datetime.date(2024, 3, 4)),
        ),
        migrations.AlterField(
            model_name='seasonticket',
            name='seasonTicketid',
            field=models.CharField(default='0B33D4C7D0', editable=False, max_length=10, primary_key=True, serialize=False),
        ),
    ]
