# Generated by Django 4.2.6 on 2024-02-03 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticketshop', '0012_alter_match_eventtime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seasonticket',
            name='seasonTicketid',
            field=models.CharField(default='59941E4832', editable=False, max_length=10, primary_key=True, serialize=False),
        ),
    ]
