# Generated by Django 4.2.6 on 2024-02-03 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticketshop', '0014_rename_sector_matchstadium_section_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seasonticket',
            name='seasonTicketid',
            field=models.CharField(default='FBF1242889', editable=False, max_length=10, primary_key=True, serialize=False),
        ),
    ]
