# Generated by Django 4.2.6 on 2024-02-04 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticketshop', '0020_alter_seasonticket_seasonticketid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seasonticket',
            name='reserved',
        ),
        migrations.AlterField(
            model_name='seasonticket',
            name='seasonTicketid',
            field=models.CharField(default='89E14FD06C', editable=False, max_length=10, primary_key=True, serialize=False),
        ),
    ]
