# Generated by Django 4.2.6 on 2024-02-04 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticketshop', '0021_remove_seasonticket_reserved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seasonticket',
            name='seasonTicketid',
            field=models.CharField(default='78BDCABA0B', editable=False, max_length=10, primary_key=True, serialize=False),
        ),
    ]
