# Generated by Django 4.2.6 on 2024-02-03 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ticketshop', '0004_alter_seasonticket_seasonticketid'),
        ('Customers', '0002_alter_shopcustomer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcustomer',
            name='orderedseasontickets',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Ticketshop.seasonticket'),
        ),
        migrations.AddField(
            model_name='shopcustomer',
            name='orderedtickets',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Ticketshop.myticket'),
        ),
    ]
