# Generated by Django 4.2.6 on 2024-02-03 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0003_shopcustomer_orderedseasontickets_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopcustomer',
            name='orderedseasontickets',
        ),
        migrations.RemoveField(
            model_name='shopcustomer',
            name='orderedtickets',
        ),
    ]
