# Generated by Django 4.2.6 on 2024-02-03 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0004_remove_shopcustomer_orderedseasontickets_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopcustomer',
            name='fanClubMember',
        ),
    ]
