# Generated by Django 4.2.6 on 2024-02-03 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0005_remove_shopcustomer_fanclubmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcustomer',
            name='reservations',
            field=models.IntegerField(default=0),
        ),
    ]
