# Generated by Django 4.2.6 on 2024-02-04 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0006_shopcustomer_reservations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopcustomer',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shopcustomer',
            name='firstName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shopcustomer',
            name='lastName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
