# Generated by Django 4.2.6 on 2024-02-04 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0007_alter_shopcustomer_age_alter_shopcustomer_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcustomer',
            name='seasonticketholder',
            field=models.BooleanField(default=False),
        ),
    ]
