# Generated by Django 4.2.5 on 2023-11-11 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopCustomer',
            fields=[
                ('personalid', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('joined', models.DateField(auto_now_add=True)),
                ('fanClubMember', models.BooleanField(default=False)),
                ('fanClubMemberid', models.CharField(blank=True, max_length=10, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
    ]
